import { Ship, RiskLevel, DocStatus, WorkloadStat } from './types';

const now = new Date();
const addHours = (h: number) => new Date(now.getTime() + h * 60 * 60 * 1000).toISOString();

export const MOCK_SHIPS: Ship[] = [
  {
    id: '1',
    name: 'COSCO STAR',
    cnName: '中远之星',
    mmsi: '412345678',
    flag: 'China',
    type: 'Container Ship',
    eta: addHours(2),
    etd: addHours(26),
    dest: '南京',
    length: 300,
    width: 45,
    draught: 9.5,
    dwt: 75000,
    riskLevel: RiskLevel.NORMAL,
    docStatus: DocStatus.APPROVED,
    lastPort: 'Singapore',
    agent: 'Ocean Agency Ltd',
  },
  {
    id: '2',
    name: 'EVER GIVEN',
    cnName: '长赐轮',
    mmsi: '356789123',
    flag: 'Panama',
    type: 'Container Ship',
    eta: addHours(5),
    etd: addHours(48),
    dest: '南京',
    length: 400,
    width: 59,
    draught: 14.8,
    dwt: 200000,
    riskLevel: RiskLevel.ATTENTION,
    riskReason: 'ETA Change > 4h',
    docStatus: DocStatus.REVIEWING,
    lastPort: 'Suez',
    agent: 'Global Marine',
  },
  {
    id: '3',
    name: 'OCEAN PIONEER',
    cnName: '海洋先锋',
    mmsi: '567890123',
    flag: 'Liberia',
    type: 'Oil Tanker',
    eta: addHours(14),
    etd: addHours(38),
    dest: '南京',
    length: 250,
    width: 44,
    draught: 16.2,
    dwt: 80000,
    riskLevel: RiskLevel.HIGH,
    riskReason: 'Blacklist Hit; High Risk Origin',
    docStatus: DocStatus.MISSING_INFO,
    lastPort: 'Bandar Abbas',
    agent: 'Sea Link Services',
  },
  {
    id: '4',
    name: 'MSC ANNA',
    cnName: '地中海安娜',
    mmsi: '234567890',
    flag: 'Liberia',
    type: 'Container Ship',
    eta: addHours(22),
    etd: addHours(40),
    dest: '南京',
    length: 330,
    width: 48,
    draught: 13.1,
    dwt: 90000,
    riskLevel: RiskLevel.NORMAL,
    docStatus: DocStatus.PENDING,
    lastPort: 'Busan',
    agent: 'Ocean Agency Ltd',
  },
  {
    id: '5',
    name: 'PACIFIC RUBY',
    cnName: '太平洋红宝石',
    mmsi: '890123456',
    flag: 'Hong Kong',
    type: 'Bulk Carrier',
    eta: addHours(28),
    etd: addHours(60),
    dest: '南京',
    length: 220,
    width: 35,
    draught: 12.4,
    dwt: 65000,
    riskLevel: RiskLevel.ATTENTION,
    riskReason: 'Doc Inconsistency',
    docStatus: DocStatus.REVIEWING,
    lastPort: 'Tokyo',
    agent: 'Pacific Shipping',
  },
  {
    id: '6',
    name: 'NORDIC STRIDER',
    cnName: '北欧行者',
    mmsi: '123123123',
    flag: 'Norway',
    type: 'Ro-Ro Cargo',
    eta: addHours(45),
    etd: addHours(70),
    dest: '南京',
    length: 200,
    width: 32,
    draught: 10.2,
    dwt: 50000,
    riskLevel: RiskLevel.NORMAL,
    docStatus: DocStatus.APPROVED,
    lastPort: 'Rotterdam',
    agent: 'Global Marine',
  },
  {
    id: '7',
    name: 'GOLDEN RAY',
    cnName: '金色光芒',
    mmsi: '999888777',
    flag: 'Marshall Islands',
    type: 'Vehicle Carrier',
    eta: addHours(50),
    etd: addHours(80),
    dest: '南京',
    length: 180,
    width: 30,
    draught: 11.7,
    dwt: 42000,
    riskLevel: RiskLevel.HIGH,
    riskReason: 'Historical Safety Issue',
    docStatus: DocStatus.PENDING,
    lastPort: 'Jacksonville',
    agent: 'Auto Trans',
  },
  {
    id: '8',
    name: 'WAN HAI 312',
    cnName: '万海312',
    mmsi: '444555666',
    flag: 'Singapore',
    type: 'Container Ship',
    eta: addHours(74),
    etd: addHours(90),
    dest: '南京',
    length: 260,
    width: 37,
    draught: 8.9,
    dwt: 38000,
    riskLevel: RiskLevel.NORMAL,
    docStatus: DocStatus.PENDING,
    lastPort: 'Kaohsiung',
    agent: 'Ocean Agency Ltd',
  }
];

export const WORKLOAD_STATS: WorkloadStat[] = [
  { timeSlot: '00:00-06:00', count: 2, riskHigh: 0, riskAttention: 0 },
  { timeSlot: '06:00-12:00', count: 5, riskHigh: 1, riskAttention: 1 },
  { timeSlot: '12:00-18:00', count: 8, riskHigh: 2, riskAttention: 2 },
  { timeSlot: '18:00-24:00', count: 4, riskHigh: 0, riskAttention: 1 },
];
